### ISSUE TITLE
Provide information about how to reset certain optimizations

### ISSUE THREAD

**Issue by vishnup95** [devangshekhawat/Fedora-40-Post-Install-Guide#11]
Hi, 

The document is wonderful and provides a lot of useful stuff to start off your fedora journey. I would like to remove certain optimizations that has been made/suggested in this document. Please add information related to that. I am noticibaly seeing a lag in wireless keyboard & mouse input after using one of the optimizations (Not sure which one).

**Comment by devangshekhawat** [comment]
did you run powertop --autotune?

**Comment by vishnup95** [comment]
> did you run powertop --autotune?

Yes.

**Comment by devangshekhawat** [comment]
then it is most likely caused by the optimizations from powertop autotune
usually sudo powertop --auto-tune is not persisted. 
so rebooting will set everything back to normal 
if the issue still persists then try running "sudo powertop" then go to tunables and change all the bluetooth related optimizations from good to bad

**Comment by vishnup95** [comment]
> then it is most likely caused by the optimizations from powertop autotune usually sudo powertop --auto-tune is not persisted. so rebooting will set everything back to normal if the issue still persists then try running "sudo powertop" then go to tunables and change all the bluetooth related optimizations from good to bad

saw this a bit late, I was still having issues after reboot. Ended up removing `powertop` and seems to be kind of better for me. I will add another after 24 hrs. Please feel free to close this!
