### ISSUE TITLE
HW video decoding support for chromium browsers

### ISSUE THREAD

**Issue by ConEstArthur** [devangshekhawat/Fedora-40-Post-Install-Guide#21]
It would be really helpful if you include method of how to enable hw video decoding support for chromium browsers.

**Comment by devangshekhawat** [comment]
Last I checked it was comparatively a very complicated process to get HW video decoding working on chromium browsers, thats why it is not included in the guide since that will stretch it way beyond the actual relevant subject matter of the guide, too much bulk would also not be ideal. If I come across a neat way to get it working then I will make sure to incorporate it into the guide.
For the time being on a personal note you can try looking into this:
https://www.reddit.com/r/Fedora/comments/1cbnsbd/i_finally_managed_to_have_hardware_accelerated/
