### ISSUE TITLE
please document how to revert modern standby

### ISSUE THREAD

**Issue by KraXen72** [devangshekhawat/Fedora-40-Post-Install-Guide#22]
i tried it but i have a 7th gen cpu and now it won't boot... i removed the grubby arg but it's still broken

**Comment by devangshekhawat** [comment]
I am sorry you had to go through that and I hope you got it back up and working.
I am removing the modern standby section entriely.

**Comment by KraXen72** [comment]
hi, yes. i had to boot off of a live, chroot and reinstall grub. I think it might've also been a combination of something else that went bad. no worries, and thanks for removing the section.

on the other hand, could you possibly look into how to set up/enable:
- proper hybernation to disk (so i can poweroff my pc and then turn it on with everything like i had)
- possibly combining that with IRST (see [arch wiki](https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Intel_Rapid_Start_Technology_(IRST))
- making sure optimus works (how to check it?)

maybe it's not relevant to fedora enough though, in which case, it's okay if you dismiss this.
thank you for all the work you've put into this guide.

**Comment by devangshekhawat** [comment]
Hi, 

### Hibernation
- Proper hibernation would be quite a struggle to setup since linux requires a swap partition for hibernation while fedora uses zswap, it might still be possible to setup hibernation but I personally hold the opinion that it would cause way too many system failures, especially when asking the users to setup separate partitions on their own for the hibernation. Even after that, hibernation has a good chance of failure if ram and swap are full at the same time.

### Optimus
- Fortunately there is no extra work needed to setup optimus, you simply need to follow the instuctions to install the nvidia drivers and optimus should be good to go. By default the iGPU would be used for all less gpu intensive tasks and the dGPU would kick in whenever need be.
